### ISSUE TITLE
styled-component 구현

### ISSUE THREAD

**Issue by eun-seong** [woowa-techcamp-2021/store-3#106]
## :hammer: 이슈 설명

style-component 구현

## 📑 체크리스트
> 수행해야 할 체크리스트

- [ ] tagged template literal 사용
- [ ] return value 설정해서 자동완성 가능하게

## 예상 소요 시간
> 이슈를 해결하기 위해 사용된 시간

- 5시간

## 🚧 주의 사항
> 기능을 구현할 때 유의깊게 살펴볼 사항

**Comment by eun-seong** [comment]
#### [TODO LIST]
- [ ] Element의 props 자동 완성 기능 하고 싶다.
- [ ] 있다가 없어진 css class는 어떻게 알 수 있을까
- [ ] `styled(BottomLineWrapper)` 형태로 받기 (현재는 `styled.div` 형태만 가능)
